[server]
enableStaticServing = true

[theme]
primaryColor = "#ae5630"
backgroundColor = "#2a2a28"
secondaryBackgroundColor = "#232220"
textColor = "#e5e5e2"
linkColor = "#e5e5e2"
borderColor = "#343330"
showWidgetBorder = true
baseRadius = "0.6rem"
font = "Styrene B"
codeFont = "Fira Code"
codeBackgroundColor = "#232322"
showSidebarBorder = true
headingFontSizes = ["40px", "32px", "24px"]
headingFontWeights = 500

[theme.sidebar]
backgroundColor = "#21201f"
secondaryBackgroundColor = "#232220"

[[theme.fontFaces]]
url = "app/static/FiraCode-VF.ttf"
family = "Fira Code"

[[theme.fontFaces]]
url = "app/static/styrene/StyreneA-Thin.otf"
family = "Styrene A"
weight = 100

[[theme.fontFaces]]
url = "app/static/styrene/StyreneA-Light.otf"
family = "Styrene A"
weight = 300

[[theme.fontFaces]]
url = "app/static/styrene/StyreneA-Regular.otf"
family = "Styrene A"
weight = 400

[[theme.fontFaces]]
url = "app/static/styrene/StyreneA-Medium.otf"
family = "Styrene A"
weight = 500

[[theme.fontFaces]]
url = "app/static/styrene/StyreneA-Bold.otf"
family = "Styrene A"
weight = 700

[[theme.fontFaces]]
url = "app/static/styrene/StyreneA-Black.otf"
family = "Styrene A"
weight = 900


[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Thin-Trial.otf"
family = "Styrene B"
weight = 100

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Light-Trial.otf"
family = "Styrene B"
weight = 300

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Regular-Trial.otf"
family = "Styrene B"
weight = 400

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Medium-Trial.otf"
family = "Styrene B"
weight = 500

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Bold-Trial.otf"
family = "Styrene B"
weight = 700

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Black-Trial.otf"
family = "Styrene B"
weight = 900

