[server]
enableStaticServing = true

[theme]
primaryColor = "#0071e3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#1d1d1f"
linkColor = "#0066cc"
borderColor = "#d2d2d7"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "12px"
font = "SF Pro Display"
codeFont = "SF Mono"
codeBackgroundColor = "#fbfbfd"
headingFontSizes = ["40px", "28px", "20px"]
headingFontWeights = 600

[theme.sidebar]
backgroundColor = "#f5f5f7"
secondaryBackgroundColor = "#f5f5f7"


[[theme.fontFaces]]
url = "app/static/sf-mono/SFMonoRegular.otf"
family = "SF Mono"
weight = 400

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Regular.otf"
family = "SF Pro Display"
weight = 400

[[theme.fontFaces]]
url = "app/static/San-Francisco-Pro-Fonts-master/SF-Pro-Display-Semibold.otf"
family = "SF Pro Display"
weight = 600
