[theme]
primaryColor = "#cc0233"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
borderColor = "#dcdcdc"
font = "Arial, sans-serif"
baseFontSize = 16
baseRadius = "none"
linkColor = "#0a3474"
linkUnderline = false
showWidgetBorder = true
headingFontSizes = ["33.17px", "22.12px", "18.06px", "16.1px"]
headingFontWeights = ["700", "700", "700"]

[theme.sidebar]
backgroundColor = "#eeeeee"
secondaryBackgroundColor = "#eeeeee"
borderColor = "#D0D0D0"
